# Generated by Django 4.2.3 on 2023-07-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentRegistration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='year',
            new_name='semester',
        ),
    ]
