# Generated by Django 4.2.3 on 2023-07-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentRegistration', '0002_rename_year_student_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
